### ISSUE TITLE
add package to void repo

### ISSUE THREAD

**Issue by kzkin** [DAINRA/ungoogled-chromium-void#22]
Why not add this package to one of the void repositories ?

**Comment by DAINRA** [comment]
Because they don't accept browser forks (you can search their github page for past requests for browsers like ungoogled-chromium or brave).

**Comment by DAINRA** [comment]
Doesn't bother me too much if it's left open, but since it's been around 30 days and there is nothing more to add I'll close it.

**Comment by KF-Art** [comment]
We, at Cereus Linux team (Void derivative), would be happy to maintain the package at our [cereus-extra](https://sourceforge.net/projects/cereus-linux/files/repos/cereus-extra/) repository (which is like a Chaotic VUR).

**Comment by siduck** [comment]
oh cool! btw @KF-Art what is the storage limit at source forge?

**Comment by KF-Art** [comment]
> oh cool! btw @KF-Art what is the storage limit at source forge?

It seems that SourceForge does not have a storage limit per project. Per file, I remember the limit was around 2GB (not sure).

We are mirroring to OSDN too, which also does not have a limit for project and per-file size limit is 4.7GB. We currently package some browsers like Waterfox, LibreWolf and Brave (in *-bin format, of course), so I think it would be no problem mantaining Ungoogled Chromium too.

**Comment by DAINRA** [comment]
A few notes:

- @siduck While that is one way of doing it, it's also a terrible way to do it since it would require a second repository and some workarounds.
- The second option would be to use the existing releases and add a step for signatures and repo data, though I'll have to do a test when I have some time since the "static" links for the latest release do some redirecting and I'm not sure xbps handles that.
- The third option would be what @KF-Art suggested. Now I'm not an expert on xbps and how the signing works, but if I understand it correctly even if @KF-Art signs the files with their key the archive itself should still be untouched (meaning the sha sums provided by the workflow at build time should still be valid).

**Comment by siduck** [comment]
@DAINRA i think you can do it in this repo itself

**Comment by KF-Art** [comment]
Yes, that's correct. XBPS handles separatedly both SHA256 checksum of the package and repository signing. So, using the binaries of the releases and signing them is doable.

**Comment by DAINRA** [comment]
@siduck There is a bigger discussion to be had about that approach, but the main points: it would force the people (there are quite a few that prefer building for themselves) to download the binaries instead of just the source template, it would also force 2 commits per release (one for building one for the actual files). Besides that there is also the problem of file limits (releases have a 2gb/file limit while repository files are only 100mb) and while it's not there yet it will be a problem in the future.

Anyway from the test I did in another repository it looks like the releases page will work fine if the needed files are added.

**Comment by siduck** [comment]
oh nvm it then @DAINRA,btw how do i know if  through a script if the release has a new update? idk much scripting but i would like to download & install new releases by a script

**Comment by DAINRA** [comment]
`curl https://api.github.com/repos/DAINRA/ungoogled-chromium-void/releases/latest` gives the release info in json format

**Comment by siduck** [comment]
> `curl https://api.github.com/repos/DAINRA/ungoogled-chromium-void/releases/latest` gives the release info in json format

thx a lot!

**Comment by siduck** [comment]
@DAINRA 

```
ERROR: [reposync] failed to fetch file `https://github.com/DAINRA/ungoogled-chromium-void/releases/latest/download/x86_64-repodata': Not Found
```

you need to have the repodate too i think

**Comment by DAINRA** [comment]
[Workflow in progress](https://github.com/DAINRA/ungoogled-chromium-void/actions/runs/2985715141) >.>

**Comment by siduck** [comment]
oh why would the CI take this much time

**Comment by siduck** [comment]
Oh nvm this is chromium :joy: 

![image](https://user-images.githubusercontent.com/59060246/188292567-a68dd930-ccbc-485a-9813-5b0999e80848.png)

I can sleep in the meantime :sleeping:
