### ISSUE TITLE
Apply musl patches from Alpine

### ISSUE THREAD

**Issue by BienAtGitHub** [DAINRA/ungoogled-chromium-void#28]
https://git.alpinelinux.org/aports/tree/community/chromium
https://git.alpinelinux.org/aports/tree/community/chromium/APKBUILD#n92
These patches should be able to prevent ungoogled-chromium (probably normal Chromium as well) from crashing with musl...

**Comment by DAINRA** [comment]
Some of those patches are already included on void but some are incompatible. Besides that there is also time lag between the releases of the 2 distributions to consider. Imo if you have crashes report them on void's github and they will be fixed if possible (might not be since the upstream doesn't support musl).

> probably normal Chromium as well

It's a safe bet that regular Chromium is affected as well, UC's patch set is small compared to the total base code of Chromium.

All in all it would be a bad idea to mix the patches.
