### ISSUE TITLE
Ungoogled Chromium doesn't do spell checking

### ISSUE THREAD

**Issue by MechDR** [DAINRA/ungoogled-chromium-void#63]
Spell checking is on, but it doesn't underline wrongly spelled words... and it doesn't do grammar checks as well I think (blue underline).

**Comment by DAINRA** [comment]
Yes it doesn't work out of the box on ungoogled chromium because language checking uses binaries and those get stripped. If you want to add the spellchecking back, follow the instructions [here](https://github.com/ungoogled-software/ungoogled-chromium/issues/188#issuecomment-643665850) (for example for english you need en-US-10-1.bdic and so on).

**Comment by DAINRA** [comment]
No you don't have to recompile, just follow the instructions in that comment I linked.

**Comment by MechDR** [comment]
This tutorial is old, `en-US-9-0.bdic` doesn't even exist, now it's just `en_US.dic`. So, I did base64 on it and placed it in `~/.config/chromium/Dictionaries`, but, it still doesn't work.

**Comment by DAINRA** [comment]
That is the wrong file. Like I wrote in the first comment the file for english spellcheck is "en-US-10-1.bdic" ([direct link](https://chromium.googlesource.com/chromium/deps/hunspell_dictionaries/+/refs/heads/main/en-US-10-1.bdic?format=TEXT))

![github com_DAINRA_ungoogled-chromium-void_issues_63](https://github.com/DAINRA/ungoogled-chromium-void/assets/90074681/1526c87b-9c3f-4443-ad4d-c14dea8354c5)

**Comment by MechDR** [comment]
Sorry, you're right, I didn't read the last part of your comment. I'll try again and get back whether it worked or not.
